<?php


namespace App\Tests\features;


use App\Entity\Stock;
use App\Http\FakeYahooFinanceAPIClient;
use App\Tests\DatabasePrimer;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

use Symfony\Component\Console\Tester\CommandTester;

class RefreshStockProfileCommandTest extends KernelTestCase
{
    protected $entityManager;


    protected function setUp(): void
    {
        $kernel =  self::bootKernel();

        DatabasePrimer::prime($kernel);

        $this->entityManager = $kernel->getContainer()->get('doctrine')->getManager();
    }


    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->entityManager->close();
        $this->entityManager = null;
    }


    /**
     * @test
     * Integgration test
     * Test the logic of our application
     * Assert we get some stock values
     */
    public function test_refresh_stock_command_behaves_corectly_if_stock_doesnt_exist(){
        //Setup
        $application = new Application(self::$kernel);
        $command = $application->find("app:refresh-stock-profile");


        //DO SOMETHING
        $commandTester = new CommandTester($command);


        //Fake test values
        FakeYahooFinanceAPIClient::$content='{"symbol":"AMZN","currency":"USD","exchangeName":"NasdaqGS","shortName":"Amazon.com, Inc.","region":"US","price":2956.94,"previousClose":2785.58,"priceChange":171.36}';



        //Flush in DB
        $commandTester->execute([
            "symbol" => "AMZN",
            "region" => "us"
            ]);


        // Retrieve from DB
        $repo = $this->entityManager->getRepository(Stock::class);
        $stock =$repo->findOneBy([
            "symbol" => "AMZN"
        ]);

        //ASSERTION

        $this->assertEquals("Amazon.com, Inc.", $stock->getShortName());
        $this->assertEquals("USD", $stock->getCurrency());
        $this->assertEquals("NasdaqGS", $stock->getExchangeName());
        $this->assertEquals("US", $stock->getRegion());
        $this->assertIsNumeric(0, $stock->getPriceChange());
        $this->assertGreaterThan(50, $stock->getPrice());
        $this->assertGreaterThan(50, $stock->getPreviousClose());

    }

}